### ISSUE TITLE
[feature-asking] Can add connections,throughput,response delay benchmarks ?

### ISSUE THREAD

**Issue by nh-live** [fwhezfwhez/tcpx#20]

**Comment by fwhezfwhez** [comment]
Already add beanchmark in README.md - 1.Start - Benchmark.

Connections and throuput depend on machine.You might test yourself.

Reponse delay depends on time cost between client side sending and server side being received. In the server, each request will cost at least 829 ns, and it will cost more as your program becomes complicated.
