### ISSUE TITLE
[feature-asking] Can you normalize the name of the network package read interface function?

### ISSUE THREAD

**Issue by nh-live** [fwhezfwhez/tcpx#21]
The following functions don't seem to clearly define what to do:
tcpx.FirstBlockOf()
tcpx.FirstBlockOfBytes()

I used this:
tcpx.UnpackToBlockFromReader()

**Comment by fwhezfwhez** [comment]
This ？
```go
func Read(r io.Reader) ([]byte,error) {
	return UnpackToBlockFromReader(r)
}
```
It doesn't fit to official reader `Read([]byte) error`
