### ISSUE TITLE
有做分布式的计划吗？

### ISSUE THREAD

**Issue by itMuYou** [fwhezfwhez/tcpx#32]
请问有做分布式的计划吗？

**Comment by fwhezfwhez** [comment]
暂时没有，短期内的计划是:

**~2020/7/10**
- 增加url路由方式，避免开发者对messageID的抢占和多余的同步流程，开发者不用关心谁该用哪个段的messageID和是否会和别人用到了同一个messageID，并且希望该方式可以逐渐替代掉messageID(但会保持兼容)。

**~2020/7/20**
- 增强Anchor类型中间件，支持同一个锚中间件多次使用Use和UnUse(目前对同一个锚中间件只支持调用一次Use()和UnUse)。

**~2020/8/1**
- 增加tcpx.Client,提供类似http/grpc范式的客户端请求方法。

要不要考虑增加对分布式的支持，还是要看需求场景，短期内可能拿不出给tcpx做这个的计划。

另外，因为微信不支持tcp，仅支持websocket，工作需要，目前在集中精力，开发websocket服务端项目，该项目使用到的websocket手脚架(wsx)也考虑在7月1号前开源。

**Comment by itMuYou** [comment]
哦哦 好的
